# -*- coding: utf-8 -*-
{
'"Type the name of a registered person \\or to add an unregistshelter click on Evacuees" ': '  "พิมพ์ชื่อของบุคคลที่ลงทะหรือเพื่อเพิ่มบุคคลที่ไม่ได้ลงทะเบียนไปที่ \\คลิกที่พักพิงบน Evacuees "  ',
'%(GRN)s Status': '%(GRN)s Status',
'%(proj4js)s definition': '%(proj4js)s definition',
'%Y-%m-%d %H:%M:%S': '%Y-%m-%d %H:%M:%S',
"'Cancel' will indicate an asset log entry did not occur": "'Cancel' will indicate an asset log entry did not occur",
'(filtered from _MAX_ total entries)': '(filtered from _MAX_ total entries)',
'* Required Fields': '* Required Fields',
'-': '-',
'2nd Nationality': '2nd Nationality',
'3W Report': '3W Report',
'_NUM_ duplicates found': '  ค้นพบ _ ซ้ำ _NUM_ รายการ   ',
'A block of rich text which could be embedded into a page, viewed as a complete page or viewed as a list of news items.   ': 'กลุ่มของข้อความที่เต็มไปด้วยเนื้อหาซึ่งสามารถฝังลงในหน้าเว็บดูเป็นหน้าเว็บที่สมบูรณ์หรือดูเป็นรายการข่าว',
'A brief description of the group (optional)': 'คำอธิบายสั้น ๆ ของกลุ่ม (ตัวเลือก)',
'A catalog of different Assessment Templates including summary information': 'แคตาล็อกของเทมเพลตการประเมินที่แตกต่างกันรวมถึงข้อมูลสรุป  ',
'A file in GPX format taken from a GPS.': 'ไฟล์ในรูปแบบ GPX ถ่ายจาก GPS',
'A Marker assigned to an individual Location is set if there is a need to override the Marker assigned to the Feature Class.  ': 'Marker ที่กำหนดให้กับแต่ละตำแหน่งจะถูกตั้งค่าหากมีความจำเป็นต้องแทนที่ Marker ที่กำหนดให้กับ Class Feature',
'A project milestone marks a significant date in the calendar which shows that progress towards the overall objective is being made.': 'ความคืบหน้าของโครงการนับเป็นวันที่สำคัญในปฏิทินซึ่งแสดงให้เห็นว่ามีการดำเนินการไปสู่เป้าหมายโดยรวม',
'A project tag helps to associate keywords with projects/tasks.': 'แท็กโครงการช่วยในการเชื่อมโยงคำหลักกับโครงการ / งาน',
'A strict location hierarchy cannot have gaps.': 'ลำดับชั้นตำแหน่งที่เข้มงวดไม่สามารถมีช่องว่างได้',
'A task is a piece of work that an individual or team can do in 1-2 days.': 'งานคือส่วนของงานที่แต่ละคนหรือทีมสามารถทำได้ภายใน 1-2 วัน',
'A unique code to identify the status': 'รหัสที่ไม่ซ้ำกันเพื่อระบุสถานะ',
'Abbreviation': '  ตัวย่อ   ',
'About': 'เกี่ยวกับ',
'About the participants': 'เกี่ยวกับผู้เข้าร่วม',
'ABOUT THIS MODULE': 'เกี่ยวกับ MODULE นี้',
'Academic': '  วิชาการ  ',
'Access': '  ทางเข้า  ',
'ACCESS DATA': 'เข้าถึงข้อมูล',
'Access denied': '  ปฏิเสธการเข้าใช้   ',
'Access Level': '  ระดับการเข้าถึง  ',
'Access Token': '  เข้าถึง Token  ',
'Access Token Secret': '  เข้าถึง Token Secret   ',
'Account added': '  เพิ่มบัญชีแล้ว   ',
'Account Label': '  ป้ายบัญชี  ',
'Account Name': '  ชื่อบัญชี  ',
'Account Registered - Please Check Your Email': '  ลงทะเบียนบัญชี - โปรดตรวจสอบอีเมลของคุณ  ',
'Acronym': '  อักษรย่อ   ',
"Acronym of the organization's name, eg. IFRC.": "Acronym of the organization's name, eg. IFRC.",
'Action created': '  สร้างการกระทำแล้ว  ',
'Action deleted': '  ลบการกระทำแล้ว   ',
'Action Details': '  รายละเอียดการดำเนินการ   ',
'Action Plan': '  แผนปฏิบัติการ  ',
'ACTION REQUIRED': 'ต้องมีการดำเนินการ',
'Action Type': '  ประเภทการทำงาน   ',
'Action updated': '  อัปเดตการดำเนินการแล้ว   ',
'Actioning officer': '  เจ้าหน้าที่ดำเนินการ   ',
'Actions': '  การปฏิบัติ   ',
'Actions assigned to me': '  การกระทำที่มอบหมายให้ฉัน   ',
'Actions managed by me': '  กิจกรรมที่ฉันจัดการ  ',
'Activate to sort column ascending': '  เปิดใช้งานเพื่อจัดเรียงคอลัมน์จากน้อยไปหามาก   ',
'Activate to sort column descending': '  เปิดใช้งานเพื่อเรียงลำดับคอลัมน์จากมากไปหาน้อย   ',
'Active': 'Active',
'Active': '  คล่องแคล่ว   ',
'Active Appointment': '  การนัดหมายที่ใช้งานอยู่  ',
'Active Missions': '  ภารกิจที่ใช้งานอยู่  ',
'Active Problems': '  ปัญหาที่ใช้งานอยู่   ',
'Active?': '  คล่องแคล่ว?  ',
'Activities': '  กิจกรรม  ',
'Activities matching Assessments': '  กิจกรรมที่ตรงกับการประเมินผล   ',
'Activities to follow up': '  กิจกรรมเพื่อติดตามผล   ',
'Activity': '  กิจกรรม  ',
'Activity added': '  เพิ่มกิจกรรมแล้ว   ',
'Activity Added': '  เพิ่มกิจกรรมแล้ว   ',
'Activity Data': '  ข้อมูลกิจกรรม  ',
'Activity Data added': '  เพิ่มข้อมูลกิจกรรมแล้ว   ',
'Activity Data removed': '  ลบข้อมูลกิจกรรมแล้ว  ',
'Activity Data updated': '  อัปเดตข้อมูลกิจกรรมแล้ว  ',
'Activity deleted': '  ลบกิจกรรมแล้ว  ',
'Activity Deleted': '  ลบกิจกรรมแล้ว  ',
'Activity Details': '  รายละเอียดกิจกรรม  ',
'Activity Focus': '  โฟกัสกิจกรรม   ',
'Activity Focus added': '  เพิ่มกิจกรรมโฟกัสแล้ว  ',
'Activity Focus deleted': '  ลบกิจกรรมโฟกัสแล้ว   ',
'Activity Focus Details': '  รายละเอียดโฟกัสของกิจกรรม  ',
'Activity Focus updated': '  อัปเดตโฟกัสกิจกรรมแล้ว   ',
'Activity Focuses': '  เน้นกิจกรรม  ',
'Activity Hours (Month)': '  ชั่วโมงกิจกรรม (เดือน)   ',
'Activity Hours (Year)': '  ชั่วโมงกิจกรรม (ปี)  ',
'Activity Name': '  ชื่อกิจกรรม  ',
'Activity Organization': '  องค์การกิจกรรม   ',
'Activity Organization Added': '  เพิ่มองค์กรกิจกรรมแล้ว   ',
'Activity Organization Deleted': '  ลบกิจกรรมกิจกรรมแล้ว   ',
'Activity Organization Updated': '  อัปเดตองค์การกิจกรรมแล้ว   ',
'Activity Organizations ': '  องค์กรกิจกรรม  ',
'Activity Report': '  รายงานกิจกรรม  ',
'Activity Report created': '  สร้างรายงานกิจกรรมแล้ว   ',
'Activity Report deleted': '  รายงานกิจกรรมถูกลบแล้ว   ',
'Activity Report updated': '  อัปเดตรายงานกิจกรรมแล้ว  ',
'Activity Reports': '  รายงานกิจกรรม  ',
'Activity Status created': '  สร้างสถานะกิจกรรมแล้ว  ',
'Activity Status deleted': '  ลบสถานะกิจกรรมแล้ว   ',
'Activity Status Details': '  รายละเอียดสถานะกิจกรรม   ',
'Activity Status updated': '  อัปเดตสถานะกิจกรรมแล้ว   ',
'Activity Statuses': '  สถานะกิจกรรม   ',
'Activity Type': '  ประเภทกิจกรรม  ',
'Activity Type added': '  เพิ่มประเภทกิจกรรมแล้ว   ',
'Activity Type Added': '  ประเภทกิจกรรมที่เพิ่ม  ',
'Activity Type added to Activity': '  ประเภทกิจกรรมที่เพิ่มลงในกิจกรรม   ',
'Activity Type added to Project Location': '  ประเภทกิจกรรมเพิ่มไปยังตำแหน่งโครงการ  ',
'Activity Type deleted': '  ลบประเภทกิจกรรมแล้ว  ',
'Activity Type Deleted': '  ลบประเภทกิจกรรมแล้ว  ',
'Activity Type removed from Activity': '  ลบประเภทกิจกรรมออกจากกิจกรรมแล้ว   ',
'Activity Type removed from Project Location': '  ลบประเภทกิจกรรมออกจากที่ตั้งโครงการแล้ว  ',
'Activity Type Updated': '  ประเภทกิจกรรมที่อัปเดตแล้ว   ',
'Activity Type updated': '  อัปเดตประเภทกิจกรรมแล้ว  ',
'Activity Types': '  ประเภทกิจกรรม  ',
'Activity Updated': '  อัปเดตกิจกรรมแล้ว  ',
'Activity updated': '  อัปเดตกิจกรรมแล้ว  ',
'Actual': '  ที่จริง  ',
'Actual Number of Beneficiaries': '  จำนวนผู้รับประโยชน์ตามจริง   ',
'Actual Progress': '  ความคืบหน้าจริง  ',
'Actual Spend': '  ใช้จริง  ',
'Actual Total': '  รวมจริง  ',
'Actual Value': '  มูลค่าตามจริง  ',
'Add': '  เพิ่ม  ',
'Add %(site_label)s Status': '  เพิ่มสถานะ %(site_label)s   ',
'Add %(staff)s': '  เพิ่ม %(staff)s   ',
'Add a new certificate to the catalog.': '  เพิ่มใบรับรองใหม่ลงในแคตตาล็อก   ',
'Add a new competency rating to the catalog.': '  เพิ่มการให้คะแนนความสามารถใหม่ลงในแคตตาล็อก  ',
'Add a new event type to the catalog.': '  เพิ่มประเภทเหตุการณ์ใหม่ลงในแคตตาล็อก  ',
'Add a new membership type to the catalog.': '  เพิ่มชนิดสมาชิกใหม่ลงในแค็ตตาล็อก  ',
'Add a new program to the catalog.': '  เพิ่มโปรแกรมใหม่ลงในแคตตาล็อก  ',
'Add a new skill type to the catalog.': '  เพิ่มประเภททักษะใหม่ลงในแคตตาล็อก  ',
'Add a new telephone type': '  เพิ่มประเภทโทรศัพท์ใหม่  ',
'Add a new vehicle category': '  เพิ่มหมวดรถใหม่  ',
'Add a new vehicle type': '  เพิ่มประเภทยานพาหนะใหม่  ',
'Add Activity': '  เพิ่มกิจกรรม   ',
'Add Activity Data': '  เพิ่มข้อมูลกิจกรรม   ',
'Add Activity Type': '  เพิ่มประเภทกิจกรรม   ',
'Add Address': 'Add Address',
'Add Address': '  เพิ่มที่อยู่   ',
'Add Affiliation': '  เพิ่ม บริษัท ในเครือ   ',
'Add all organizations which are involved in different roles in this project  ': '  เพิ่มองค์กรทั้งหมดที่เกี่ยวข้องกับบทบาทต่างๆในโครงการนี้   ',
'Add Annual Budget': '  เพิ่มงบประมาณรายปี   ',
'Add another': '  เพิ่มอีกหนึ่ง  ',
'Add Appraisal': '  เพิ่มการประเมิน  ',
'Add Assessment': '  เพิ่มการประเมิน  ',
'Add Asset': '  เพิ่มเนื้อหา   ',
'Add Award': '  เพิ่มรางวัล  ',
'Add Beneficiaries': '  เพิ่มผู้รับประโยชน์  ',
'Add Beneficiary Data': '  เพิ่มข้อมูลผู้รับเงิน  ',
'Add Bookmark': '  เพิ่มบุ๊กมาร์ก   ',
'Add Branch Organization': '  เพิ่มองค์กรสาขา  ',
'Add Bundle': '  เพิ่ม Bundle   ',
'Add Camp': '  เพิ่มค่าย  ',
'Add Camp Service': '  เพิ่มบริการ Camp   ',
'Add Camp Status': '  เพิ่มสถานะค่าย   ',
'Add Camp Type': '  เพิ่มประเภท Camp   ',
'Add Campaign Message': '  เพิ่มข้อความแคมเปญ   ',
'Add Certificate for Course ': '  เพิ่มใบรับรองสำหรับหลักสูตร  ',
'Add Certification': '  เพิ่มการรับรอง   ',
'Add Circle': '  เพิ่มแวดวง   ',
'Add Community': '  เพิ่มชุมชน   ',
'Add Contact': '  เพิ่มผู้ติดต่อ   ',
'Add Contact Informatio': '  เพิ่มข้อมูลการติดต่อ   ',
'Add Credential': '  เพิ่มข้อมูลรับรอง  ',
'Add Data to Theme Layer': '  เพิ่มข้อมูลลงในเลเยอร์ธีม  ',
'Add Demographic': '  เพิ่มข้อมูลประชากร   ',
'Add Demographic Data': '  เพิ่มข้อมูลประชากร   ',
'Add Disciplinary Action': '  เพิ่มการลงโทษทางวินัย  ',
'Add Disciplinary Action Type': '  เพิ่มประเภทการดำเนินการทางวินัย  ',
'Add Distribution': '  เพิ่มการกระจาย   ',
'Add Education Detail': '  เพิ่มรายละเอียดการศึกษา  ',
'Add Education Level': '  เพิ่มระดับการศึกษา   ',
'Add Effort': '  เพิ่มความพยายาม  ',
'Add Experience ': '  เพิ่มประสบการณ์  ',
'Add Facebook Account': '  เพิ่มบัญชี Facebook  ',
'Add Goal': '  เพิ่มเป้าหมาย  ',
'Add Google Cloud Messaging Settings': '  เพิ่มการตั้งค่าการรับส่งข้อความใน Google Cloud   ',
'Add Hazard': '  เพิ่มอันตราย   ',
'Add Hours': '  เพิ่มชั่วโมง   ',
'Add Household Details': '  เพิ่มรายละเอียดครัวเรือน   ',
'Add Household Member': '  เพิ่มสมาชิกในครัวเรือน   ',
'Add Identity': '  เพิ่มข้อมูลเฉพาะตัว  ',
'Add Image': 'Add Image',
'Add Image': '  ใส่รูปภาพ  ',
'Add Impact': '  เพิ่มผลกระทบ   ',
'Add Impact Type': '  เพิ่มประเภทผลกระทบ   ',
'Add Indicator': '  เพิ่มตัวบ่งชี้   ',
'Add Indicator Criterion': '  เพิ่มเกณฑ์การระบุตัวบ่งชี้   ',
'Add Indicator Data': '  เพิ่มข้อมูลตัวบ่งชี้   ',
'Add Item': '  เพิ่มรายการ  ',
'Add Item to Commitment': '  เพิ่มรายการไปยังคำสัญญา  ',
'Add Item to Kit': 'เพิ่มรายการลงใน Kit  ',
'Add Item to Request': 'เพิ่มรายการไปยังคำขอ   ',
'Add Item to Shipment': '  เพิ่มรายการในการจัดส่ง   ',
'Add Item to Stock  ': '  เพิ่มรายการไปยัง Stock   ',
'Add Keyword': '  เพิ่มคำค้นหา   ',
'Add Kit': '  เพิ่ม Kit  ',
'Add Layer to this Profile': '  เพิ่มเลเยอร์ลงในโปรไฟล์นี้   ',
'Add Line': '  เพิ่มบรรทัด  ',
'Add Location': 'Add Location',
'Add Location': '  เพิ่มสถานที่   ',
'Add Log Entry': '  เพิ่มรายการบันทึก  ',
'Add Member': '  เพิ่มสมาชิก  ',
'Add Membership': '  เพิ่มสมาชิก  ',
'Add Metadata': '  เพิ่มข้อมูลเมตา  ',
'Add Mobile Commons Settings': '  เพิ่มการตั้งค่า Mobile Commons   ',
'Add Modem Channel': '  เพิ่มช่องโมเด็ม  ',
'Add New Information': '  เพิ่มข้อมูลใหม่  ',
'Add New Vehicle Type': '  เพิ่มประเภทยานใหม่   ',
'Add Order': '  เพิ่มคำสั่งซื้อ  ',
'Add Organization': '  เพิ่มองค์กร  ',
'Add Organization Domain': '  เพิ่มโดเมนองค์กร   ',
'Add Organization Needs': 'Add Organization Needs',
'Add Organization Needs': '  เพิ่มความต้องการขององค์กร  ',
'Add Organization to Activity': '  เพิ่มองค์กรสู่กิจกรรม  ',
'Add Organization to Project': '  เพิ่มองค์กรไปยังโครงการ  ',
'Add Outcome': '  เพิ่มผลลัพธ์   ',
'Add Output': '  เพิ่มเอาท์พุท  ',
'Add Participant': '  เพิ่มผู้เข้าร่วม   ',
'Add People': '  เพิ่มบุคคล   ',
'Add People to Commitment': '  เพิ่มบุคคลเพื่อผูกพัน  ',
'Add Person to Commitment': '  เพิ่มบุคคลเพื่อผูกพัน  ',
'Add Photo': 'Add Photo',
'Add Photo': '  เพิ่มรูปภาพ  ',
'Add PoI': '  เพิ่ม PoI  ',
'Add Point': '  เพิ่มจุด   ',
'Add Polygon': '  เพิ่มรูปหลายเหลี่ยม  ',
'Add Professional Experience': '  เพิ่มประสบการณ์วิชาชีพ   ',
'Add Profile Configuration for this Layer': '  เพิ่มการกำหนดค่าส่วนกำหนดค่าสำหรับเลเยอร์นี้   ',
'Add Project Needs': '  เพิ่มความต้องการของโครงการ   ',
'Add Recipient': '  เพิ่มผู้รับ  ',
'Add Record ': '  เพิ่มบันทึก  ',
'Add Reference Document ': '  เพิ่มเอกสารอ้างอิง   ',
'Add Region ': '  เพิ่มภูมิภาค   ',
'Add Resource': '  เพิ่มแหล่งข้อมูล   ',
'Add Response Summary':'  เพิ่มการสรุปการตอบสนอง   ',
'Add RSS Channel': '  เพิ่มช่อง RSS  ',
'Add Salary': '  เพิ่มเงินเดือน   ',
'Add Sector': '  เพิ่มกลุ่ม   ',
'Add Service': '  เพิ่มบริการ  ',
'Add Shelter': '  เพิ่มที่พักพิง   ',
'Add Site Needs ': '  เพิ่มความต้องการของไซต์  ',
'Add Situation Report': '  เพิ่มรายงานสถานการณ์   ',
'Add Skill': '  เพิ่มทักษะ   ',
'Add Skill Equivalence': '  เพิ่มความเท่าเทียมกันของทักษะ  ',
'Add Skill to Request': '  เพิ่มทักษะในการขอ  ',
'Add Stock to Warehouse': '  เพิ่มสต็อกลงในคลังสินค้า   ',
'Add strings manually': '  เพิ่มสตริงด้วยตนเอง  ',
'Add strings manually through a text file': '  เพิ่มสตริงด้วยตนเองผ่านไฟล์ข้อความ   ',
'Add Target': '  เพิ่มเป้าหมาย  ',
'Add Team': '  เพิ่มทีม   ',
'Add Team Member': '  เพิ่มสมาชิกทีม   ',
'Add Telephone': '  เพิ่มโทรศัพท์  ',
'Add Telephone Type': '  เพิ่มประเภทโทรศัพท์  ',
'Add Theme': '  เพิ่มธีม   ',
'Add this entry': '  เพิ่มรายการนี้   ',
'Add to a Team': '  เพิ่มลงในทีม   ',
'Add to Bin': '  เพิ่มลงในถัง   ',
'Add Trainee': '  เพิ่มผู้ฝึกงาน   ',
'Add Training': '  เพิ่มการฝึกอบรม  ',
'Add Translation Language': '  เพิ่มภาษาการแปล  ',
'Add Twilio Channel': '  เพิ่มช่อง Twilio   ',
'Add Twitter account': '  เพิ่มบัญชี Twitter   ',
'Add Twitter Search Query': '  เพิ่มข้อความค้นหาใน Twitter  ',
'Add Type of People': '  เพิ่มประเภทบุคคล   ',
'Add Vehicle': '  เพิ่มรถยนต์  ',
'Add Vehicle Category': '  เพิ่มหมวดยานพาหนะ  ',
'Add Vehicle Details': '  เพิ่มรายละเอียดยานพาหนะ  ',
'Add Vehicle Type': '  เพิ่มประเภทยานพาหนะ  ',
'Add...': '  เพิ่ม...   ',
'Added to Forum': '  เพิ่มลงในฟอรัมแล้ว   ',
'Added to Group': '  เพิ่มลงในกลุ่มแล้ว   ',
'Added to Team': '  เพิ่มลงในทีมแล้ว   ',
'Additional Beds / 24hrs': '  เตียงเสริม / 24 ชั่วโมง  ',
'Additional relevant information': '  ข้อมูลที่เกี่ยวข้องเพิ่มเติม   ',
'Address': '  ที่อยู่  ',
'Address added': '  เพิ่มที่อยู่แล้ว   ',
'Address deleted': '  ลบที่อยู่แล้ว  ',
'Address Details': '  รายละเอียดที่อยู่  ',
'Address Found': '  พบที่อยู่  ',
'Address Mapped ': '  กำหนดที่อยู่   ',
'Address NOT Found': '  ไม่พบที่อยู่   ',
'Address NOT Mapped': '  ที่อยู่ NOT Mapped   ',
'Address Type': '  ประเภทที่อยู่  ',
'Address updated': '  อัปเดตที่อยู่แล้ว  ',
'Addresses': '  ที่อยู่  ',
'Adequate': '  เพียงพอ  ',
'Adjust Item Quantity   ': '  ปรับจำนวนสินค้า  ',
'Adjust Stock': '  ปรับสต็อก  ',
'Adjust Stock Item': '  ปรับสต็อกสินค้า  ',
'Adjust Stock Levels': '  ปรับระดับสต็อค   ',
'Adjustment created': '  ปรับเปลี่ยนแล้ว  ',
'Adjustment deleted': '  ปรับการลบแล้ว  ',
'Adjustment modified': '  ปรับปรุงการปรับเปลี่ยนแล้ว   ',
'Admin': '  ผู้ดูแลระบบ  ',
'ADMIN Permissions can not be changed.': 'สิทธิ์ ADMIN ไม่สามารถเปลี่ยนแปลงได้',
'Administration ': '  การบริหาร  ',
'Administrative support cost': '  ค่าใช้จ่ายในการบริหาร  ',
'Administrative Units': '  หน่วยงานธุรการ   ',
'Admission from ': '  เข้าชมจาก  ',
'Admissions': '  การรับสมัคร  ',
'Admissions/24hrs': '  การรับสมัคร / 24   ',
'Adolescent (12-20)   ': '  วัยรุ่น (12-20)  ',
'Adult': '  ผู้ใหญ่  ',
'Adult (21-50)': '  ผู้ใหญ่ (21-50)  ',
'Adult ICU': '  ICU สำหรับผู้ใหญ่  ',
'Adult Psychiatric': '  ผู้ใหญ่จิตเวชศาสตร์  ',
'Adults ': '  ผู้ใหญ่  ',
'Advice at Check-in ': '  คำแนะนำในการเช็คอิน  ',
'Advice at Check-out': '  คำแนะนำในการเช็คเอาท์  ',
'Advice at ID Check ': '  คำแนะนำในการตรวจสอบรหัส  ',
'Advisory': '  ที่ปรึกษา  ',
'Advocacy': '  ทนาย   ',
'Affiliation added': '  เพิ่มพันธมิตรแล้ว  ',
'Affiliation deleted': '  ลบพันธมิตรแล้ว   ',
'Affiliation Details': '  รายละเอียด Affiliation   ',
'Affiliation updated': '  อัปเดต Affiliation แล้ว  ',
'Affiliations': '  บริษัท ในเครือ   ',
'Age': '  อายุ   ',
'Age Group': '  กลุ่มอายุ  ',
'Age Group added': '  กลุ่มอายุเพิ่มขึ้น   ',
'Age Group deleted': '  ลบกลุ่มอายุแล้ว  ',
'Age Group Details': '  รายละเอียดกลุ่มอายุ  ',
'Age Group updated': '  อัปเดตกลุ่มอายุแล้ว  ',
'Age Groups': '  กลุ่มอายุ  ',
'Aggregate': '  สรุป   ',
'Aggregation Type': '  ประเภทรวม  ',
'Agriculture': '  การเกษตร   ',
'Air Transport Service': '  บริการขนส่งทางอากาศ  ',
'Aircraft Maximum Size': '  ขนาดเครื่องบินสูงสุด   ',
'Airport': 'Airport',
'Airport': '  สนามบิน  ',
'Airport added': 'Airport added',
'Airport added': '  เพิ่มสนามบินแล้ว   ',
'Airport deleted': '  ลบสนามบินแล้ว  ',
'Airport Details': '  รายละเอียดสนามบิน  ',
'Airport updated': '  อัปเดตสนามบินแล้ว  ',
'Airports': '  สนามบิน  ',
'Airtime Provider': '  ผู้ให้บริการระบบ Airtime   ',
'Alert': '  เตือนภัย   ',
'Alert added': '  เพิ่มการแจ้งเตือนแล้ว  ',
'Alert deleted': '  ลบการแจ้งเตือนแล้ว   ',
'Alert Details': '  รายละเอียดการแจ้งเตือน   ',
'Alert Details updated': '  อัปเดตรายละเอียดการเตือนแล้ว   ',
'Alerted': '  การแจ้งเตือน   ',
'Alerts ': '  การแจ้งเตือน   ',
'All': 'All',
'ALL': 'ทั้งหมด',
'All': '  ทั้งหมด  ',
'All data provided by the Sahana Software Foundation from this site is licensed under a Creative Commons Attribution license. However, not all data originates here. Please consult the source field of each entry.   ': '  ข้อมูลทั้งหมดที่ได้รับจากมูลนิธิ Sahana Software จากเว็บไซต์นี้ได้รับอนุญาตภายใต้ใบอนุญาตครีเอทีฟคอมมอนส์ อย่างไรก็ตามข้อมูลทั้งหมดไม่ได้มาที่นี่ โปรดดูที่ฟิลด์ต้นทางของแต่ละรายการ   ',
'All Entities': '  เอนทิตีทั้งหมด   ',
'All Inbound & Outbound Messages are stored here': '  ข้อความขาเข้าและขาออกทั้งหมดจะถูกเก็บไว้ที่นี่   ',
'All Open Tasks': '  งานที่เปิดทั้งหมด  ',
'All Records': '  บันทึกทั้งหมด  ',
'All Resources': '  แหล่งข้อมูลทั้งหมด   ',
'All selected': '  เลือกทั้งหมด   ',
'All Tasks': '  งานทั้งหมด   ',
'Allergic': '  แพ้  ',
'Allergies': '  โรคภูมิแพ้   ',
'Allocate Group': '  จัดสรรกลุ่ม  ',
'Allocated': '  จัดสรร   ',
'Allocation': '  การจัดสรร  ',
'Allocation Details': '  รายละเอียดการจัดสรร  ',
'Allow records to be synchronized even if the remote record has a different unique identifier (UUID), and update local identifiers. Useful in active repositories when there are known duplicates in the remote database. Must be activated before the first synchronization run to take effect.': 'Allow records to be synchronized even if the remote record has a different unique identifier (UUID), and update local identifiers. Useful in active repositories when there are known duplicates in the remote database. Must be activated before the first synchronization run to take effect.',
'Allowance Information': '  ข้อมูลค่าเผื่อ   ',
'Allowance Information added': '  เพิ่มข้อมูลเบี้ยประกันภัยแล้ว  ',
'Allowance Information deleted': '  ลบข้อมูลค่าเผื่อแล้ว   ',
'Allowance Information updated': '  ข้อมูลอัปเดตถูกอัปเดตแล้ว  ',
'Allowance Payment': '  การจ่ายเงินค้ำประกัน   ',
'Allowance Suspended': '  เบี้ยเลี้ยงที่ถูกระงับ   ',
'Allows a budget to be developed based on staff & equipment costs, including any admin overheads.': '  ช่วยให้สามารถพัฒนางบประมาณตามค่าใช้จ่ายพนักงานและอุปกรณ์รวมทั้งค่าโสหุ้ยของผู้ดูแลระบบ   ',
'Already a Member': '  เป็นสมาชิกแล้ว   ',
'Alternate Name': '  ชื่อสำรองของ   ',
'Alternative Item added': '  เพิ่มรายการทางเลือกแล้ว  ',
'Alternative Item deleted': '  ลบรายการทางเลือกแล้ว   ',
'Alternative Item Details': '  รายละเอียดสินค้าทางเลือก   ',
'Alternative Item updated': '  ปรับปรุงรายการทางเลือกแล้ว   ',
'Alternative Items': '  รายการทางเลือก   ',
'Always update': '  อัปเดตเสมอ   ',
'Am': ' ก่อนเที่ยง   ',
'AM': ' ก่อนเที่ยง   ',
'Ambulance Service': '  บริการรถพยาบาล   ',
'Amount': '  จำนวน  ',
'Amount of the Project Budget spent at this location': '  จำนวนงบประมาณโครงการที่ใช้ในสถานที่นี้   ',
'An Assessment Template can be selected to create a Disaster Assessment. Within a Disaster Assessment, responses can be collected and results can analyzed as tables, charts and maps': '  คุณสามารถเลือกเทมเพลตการประเมินเพื่อสร้างการประเมินความเสียหายได้ ในการประเมินภัยพิบัติสามารถเก็บรวบรวมการตอบสนองและสามารถวิเคราะห์ผลเป็นตารางแผนภูมิและแผนที่   ',
'An error occured, please %(reload)s the page.': '  เกิดข้อผิดพลาดโปรด% (โหลดซ้ำ) ของหน้า  ',
'An ESRI Shapefile (zipped)': '  รูปแบบ ESRI (บีบอัด)  ',
'An individual/team to do in 1-2 days': '  แต่ละทีม / ทีมทำใน 1-2 วัน   ',
'An Item Category must have a Code OR a Name.': '  หมวดหมู่รายการต้องมีรหัสหรือชื่อ   ',
'Analyze with KeyGraph': '  วิเคราะห์ด้วย KeyGraph   ',
'And': '  และ  ',
'Annual Budget': '  งบประมาณรายปี  ',
'Annual Budget deleted': '  ลบงบประมาณรายปีแล้ว  ',
'Annual Budget updated': '  อัปเดตงบประมาณรายปีแล้ว  ',
'Annual Budgets': '  งบประมาณรายปี  ',
'Anonymous': '  ไม่ระบุชื่อ  ',
'Anonymous user': '  ผู้ใช้ที่ไม่ระบุตัวตน  ',
'Answer': '  ตอบ  ',
'Antibiotics available': '  มียาปฏิชีวนะ   ',
'Antibiotics needed per 24h': '  ยาปฏิชีวนะที่จำเป็นต่อ 24 ชั่วโมง  ',
'ANY': 'ใด ๆ',
'Any': '  ใด   ',
'API KEY': 'คีย์ API',
'Applicable to projects in Pacific countries only': '  ใช้ได้กับโครงการในประเทศแถบแปซิฟิกเท่านั้น   ',
'Application': '  ใบสมัคร  ',
'Appointment added': '  นัดหมายเพิ่มแล้ว   ',
'Appointment deleted': '  การนัดหมายถูกลบแล้ว  ',
'Appointment Details': '  รายละเอียดการนัดหมาย   ',
'Appointment Type': '  ประเภทนัดหมาย  ',
'Appointment Type added ': '  เพิ่มประเภทการนัดหมายแล้ว  ',
'Appointment Type deleted': '  ลบประเภทการนัดหมายแล้ว   ',
'Appointment Type Details': '  รายละเอียดประเภทการแต่งตั้ง  ',
'Appointment Type updated': '  ประเภทนัดหมายได้รับการปรับปรุงแล้ว   ',
'Appointment Types': '  ประเภทนัดหมาย  ',
'Appointment updated': '  ได้รับการแต่งตั้งแล้ว  ',
'Appointments': '  นัดหมาย  ',
'Appointments with future dates can not be marked as completed  ': '  การนัดหมายที่มีวันที่ในอนาคตไม่สามารถทำเครื่องหมายว่าเสร็จสิ้นได้  ',
'Appraisal added': '  การประเมินเพิ่ม  ',
'Appraisal deleted': '  การประเมินลบแล้ว   ',
'Appraisal Details': '  รายละเอียดการประเมิน   ',
'Appraisal updated': '  อัปเดตการประเมินแล้ว   ',
'Appraisals ': '  การประเมินผล   ',
'Approve': 'Approve',
'Approve': '  อนุมัติ  ',
'Approved': '  ได้รับการอนุมัติ   ',
'Approved By': '  อนุญาตโดย  ',
'Approver': '  ผู้อนุมัติ   ',
'ArcGIS REST Layer': 'ArcGIS REST Layer',
'Archived': '  เก็บถาวร   ',
'Archived Cases': '  กรณีที่เก็บไว้   ',
'Are you sure you want to commit to this request and send a shipment?': '  คุณแน่ใจหรือไม่ว่าต้องการจะยอมรับคำขอนี้และส่งการจัดส่ง  ',
'Are you sure you want to create a new request as a copy of this one?': '  คุณแน่ใจหรือไม่ว่าต้องการสร้างคำขอใหม่เป็นสำเนานี้   ',
'Are you sure you want to delete this record?': '  คุณแน่ใจหรือไม่ว่าต้องการลบระเบียนนี้  ',
'Are you sure you want to send a shipment for this request?': '  คุณแน่ใจหรือไม่ว่าต้องการส่งการขนส่งสำหรับคำขอนี้  ',
'Are you sure you want to send this shipment?': '  คุณแน่ใจหรือไม่ว่าต้องการส่งการจัดส่งนี้   ',
'Are you susbscribed?': '  คุณกำลังหงุดหงิดหรือไม่?   ',
'Areas': '  พื้นที่  ',
'Arguments': '  ข้อโต้แย้ง   ',
'Arrival Date': '  วันที่มาถึง  ',
'Arrived': 'Arrived',
'Arrived': '  มาถึง  ',
'As of yet, no sections have been added to this template.': '  ยังไม่มีการเพิ่มส่วนใด ๆ ลงในเทมเพลตนี้  ',
'Asphalt': '  ยางมะตอย   ',
'Assessment': '  การประเมินผล   ',
'Assessment added': '  การประเมินเพิ่ม  ',
'Assessment admin level': '  ระดับผู้ดูแลระบบการประเมินผล   ',
'Assessment Answer added': '  ตอบเพิ่มแล้ว   ',
'Assessment Answer deleted': '  ลบการตอบคำถามแล้ว  ',
'Assessment Answer Details': '  รายละเอียดการตอบแบบประเมิน   ',
'Assessment Answer updated': '  ปรับปรุงคำตอบแล้ว  ',
'Assessment Answers': '  คำตอบในการประเมิน  ',
'Assessment deleted': '  การประเมินลบแล้ว   ',
'Assessment Details': '  รายละเอียดการประเมิน   ',
'Assessment Question added': '  เพิ่มคำถามการประเมินแล้ว   ',
'Assessment Question deleted': '  ลบคำถามการประเมินแล้ว  ',
'Assessment Question Details': '  รายละเอียดคำถามการประเมิน  ',
'Assessment Question updated': '  อัปเดตคำถามประเมินแล้ว   ',
'Assessment Questions': '  คำถามการประเมิน  ',
'Assessment removed': '  ลบออกแล้ว  ',
'Assessment Targets': '  เป้าหมายการประเมิน   ',
'Assessment Template added': '  เพิ่มเทมเพลตการประเมินแล้ว   ',
'Assessment Template deleted': '  ลบเทมเพลตการประเมินแล้ว  ',
'Assessment Template Details': '  รายละเอียดเทมเพลตการประเมิน  ',
'Assessment Template updated': '  อัปเดตเทมเพลตการประเมินแล้ว  ',
'Assessment Templates': '  เทมเพลตการประเมิน  ',
'Assessment timeline': '  ระยะเวลาการประเมิน   ',
'Assessment updated': '  อัปเดตการประเมินแล้ว   ',
'Assessments': '  การประเมินผล   ',
'Asset': '  สินทรัพย์  ',
'Asset added': '  เพิ่มเนื้อหาแล้ว   ',
'Asset deleted': '  ลบเนื้อหาแล้ว  ',
'Asset Details': '  รายละเอียดสินทรัพย์  ',
'Asset Item ': '  รายการสินทรัพย์  ',
'Asset Log': '  บันทึกสินทรัพย์  ',
'Asset Log Details': '  รายละเอียดบันทึกสินทรัพย์  ',
'Asset Log Empty': '  ไฟล์บันทึกสินทรัพย์ว่างเปล่า   ',
'Asset Log Entry deleted': '  บันทึกรายการบันทึกสินทรัพย์แล้ว  ',
'Asset Log Entry updated': '  อัปเดตบันทึกข้อมูลสินทรัพย์แล้ว  ',
'Asset Number': '  หมายเลขสินทรัพย์   ',
'Asset removed': '  ลบเนื้อหาแล้ว  ',
'Asset updated': '  อัปเดตเนื้อหาแล้ว  ',
'Assets': 'Assets',
'Assets': '  สินทรัพย์  ',
'Assets are resources which are not consumable but are expected back, so they need tracking.': '  สินทรัพย์เป็นแหล่งข้อมูลที่ไม่สามารถบริโภคได้ แต่คาดว่าจะกลับมาจึงต้องมีการติดตาม  ',
'Assign': '  กำหนด  ',
'Assign %(case)s': '  กำหนด% (กรณี) s  ',
'Assign %(staff)s': '  กำหนด% (พนักงาน) s   ',
'Assign another Role': '  กำหนดบทบาทอื่น   ',
'Assign Asset': '  กำหนดสินทรัพย์   ',
'Assign Facility': '  มอบหมายสถานที่   ',
'Assign Human Resource': '  มอบหมายทรัพยากรบุคคล   ',
'Assign People': '  มอบหมายบุคคล   ',
'Assign People to this Request': '  กำหนดบุคคลในคำขอนี้  ',
'Assign Role to a User': '  กำหนดบทบาทให้กับผู้ใช้   ',
'Assign Roles': '  กำหนดบทบาท   ',
'Assign Staff': '  กำหนดพนักงาน   ',
'Assign Team': '  มอบหมายทีม   ',
'Assign to': '  กำหนดให้   ',
'Assign to Facility/Site': '  กำหนดให้สถานที่ / ไซต์   ',
'Assign to Incident': '  กำหนดให้เหตุการณ์  ',
'Assign to Organization   ': '  มอบหมายให้องค์กร   ',
'Assign to Person': '  กำหนดให้กับบุคคล   ',
'Assigned': '  ที่ได้รับมอบหมาย   ',
'Assigned By': '  มอบหมายโดย   ',
'Assigned Human Resources   ': '  มอบหมายทรัพยากรบุคคล   ',
'Assigned Roles': '  บทบาทที่ได้รับมอบหมาย  ',
'Assigned Teams': '  มอบหมายทีม   ',
'Assigned To': '  ได้รับมอบหมายให้   ',
'Assigned to': '  ได้รับมอบหมายให้   ',
'Assigned to Facility/Site': '  มอบหมายให้สถานที่ / ไซต์   ',
'Assigned to Organization': '  มอบหมายให้องค์การ  ',
'Assigned to Person': '  กำหนดให้กับบุคคล   ',
'Assignments': '  การมอบหมาย   ',
'Associate Event': '  เชื่อมโยงเหตุการณ์   ',
'Association': '  สมาคม  ',
'Assume this event type if no type was specified for an event': '  สมมติว่าประเภทเหตุการณ์นี้หากไม่มีการระบุประเภทสำหรับเหตุการณ์   ',
'At or below %s ': '  ที่หรือต่ำกว่า% s  ',
'At same level': '  ในระดับเดียวกัน  ',
'Attachment': '  ความผูกพัน   ',
'Attachments': '  สิ่งที่แนบมา   ',
'Attributes': '  แอตทริบิวต์  ',
'Attribution': '  การแสดงที่มา   ',
'AUTH TOKEN': 'AUTH TOKEN',
'Authentication Required': '  ต้องการการตรวจสอบสิทธิ์  ',
'Author': '  ผู้เขียน   ',
'Auto start': '  เริ่มต้นอัตโนมัติ  ',
'Automatic Message': '  ข้อความอัตโนมัติ   ',
'Automatically create this appointment for new cases': '  สร้างการแต่งตั้งนี้สำหรับกรณีใหม่โดยอัตโนมัติ  ',
'Availability': '  ความพร้อมใช้งาน  ',
'Availability of bath handicap facilities': '  ความพร้อมของสิ่งอำนวยความสะดวกอุปการะอาบน้ำ  ',
'Availability of shower handicap facilities': '  ห้องอาบน้ำฝักบัวพร้อมใช้งาน  ',
'Available': '  ใช้ได้   ',
'Available': '  ที่มีจำหน่าย',
'Available Alternative Inventories': '  สินค้าคงคลังทางเลือกที่มีจำหน่าย   ',
'Available Bath': '  มีอ่างอาบน้ำ   ',
'Available Beds': '  มีเตียงนอน   ',
'Available Capacity': '  กำลังการผลิตที่มีอยู่  ',
'Available Capacity (Day)': '  กำลังการผลิตที่มีจำหน่าย (วัน)   ',
'Available Capacity (Night)': '  ความจุที่มีจำหน่าย (กลางคืน)   ',
'Available Databases and Tables': '  ฐานข้อมูลและตารางที่พร้อมใช้งาน  ',
'Available Forms': '  แบบฟอร์มที่มีให้',
'Available in Viewer?': '  มีใน Viewer หรือไม่?   ',
'Available Inventories': '  สินค้าคงคลังที่มีจำหน่าย   ',
'Available Shower': '  มีฝักบัว   ',
'Avalanche': '  หิมะถล่ม   ',
'Average': '  เฉลี่ย   ',
'Average': '  เฉลี่ย   ',
'Average Monthly Income': '  รายได้เฉลี่ยต่อเดือน   ',
'Average Weekly Income': '  รายได้เฉลี่ยต่อสัปดาห์   ',
'Award': '  รางวัล   ',
'Award added': '  เพิ่มรางวัลแล้ว  ',
'Award deleted': '  ลบรางวัลแล้ว   ',
'Award Details': '  รายละเอียดรางวัล   ',
'Award removed': '  ลบรางวัลแล้ว   ',
'Award Type': '  ประเภทรางวัล   ',
'Award updated': '  ได้รับการปรับปรุงแล้ว  ',
'Awarding Body': '  การมอบรางวัล   ',
'Awards ': '  รางวัล   ',
'Awareness raising': '  การสร้างความตระหนัก  ',
}
